# Generated by Django 5.1.6 on 2025-02-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_User', models.CharField(help_text='ФИО', max_length=30)),
                ('Password', models.CharField(help_text='Пароль', max_length=30)),
                ('Login', models.CharField(help_text='Логин', max_length=20)),
                ('VK_id', models.CharField(help_text='id ВК', max_length=30)),
                ('Number_of_events_attended', models.IntegerField()),
                ('Number_of_group', models.CharField(help_text='Номер группы', max_length=6)),
                ('User_photo', models.ImageField(blank=True, upload_to=None)),
            ],
        ),
    ]
