# Generated by Django 5.1.6 on 2025-02-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Name_User',
            field=models.CharField(max_length=30, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Number_of_group',
            field=models.CharField(max_length=7, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='VK_id',
            field=models.CharField(max_length=30, verbose_name='ВК ID'),
        ),
    ]
