# Generated by Django 5.1.6 on 2025-02-18 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Number_of_group',
            field=models.CharField(help_text='Номер группы', max_length=7),
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('isOrganizer', models.BooleanField()),
                ('uuid', models.ForeignKey(help_text='Пользователь', on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'verbose_name': 'User role',
                'ordering': ['id'],
            },
        ),
    ]
