# Generated by Django 5.1.6 on 2025-02-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_name_user_alter_user_number_of_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Number_of_events_attended',
            field=models.IntegerField(default=0, verbose_name='Количество посещенных мероприятий'),
        ),
        migrations.AlterField(
            model_name='user',
            name='User_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m/%d/%user_id/', verbose_name='Фоторгафия'),
        ),
    ]
