# Generated by Django 5.1.6 on 2025-02-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title_event', models.TextField(help_text='Название мероприятия')),
                ('description_Event', models.TextField(help_text='Описание мероприятия')),
                ('rate', models.PositiveSmallIntegerField()),
                ('Event_photo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
