# Generated by Django 5.1.6 on 2025-02-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Ok'), (2, 'Fine'), (3, 'Good'), (4, 'Amaizing'), (5, 'Incredible')]),
        ),
    ]
