# Generated by Django 5.1.6 on 2025-02-21 05:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0002_alter_event_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rate',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата проведения мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_place',
            field=models.TextField(default=None, help_text='Место проведеиня мероприятия'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=None),
        ),
    ]
