# Generated by Django 5.1.6 on 2025-03-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0003_question_answeroption_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventrating',
            name='dislikes',
            field=models.TextField(blank=True, null=True, verbose_name='Что вам не понравилось'),
        ),
        migrations.AddField(
            model_name='eventrating',
            name='likes',
            field=models.TextField(blank=True, null=True, verbose_name='Что вам понравилось'),
        ),
    ]
