# Generated by Django 5.1.6 on 2025-03-12 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0004_remove_event_event_rate_event_event_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Мероприятие'},
        ),
        migrations.RemoveField(
            model_name='event',
            name='prousers_members',
        ),
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='organized_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='users_members',
            field=models.ManyToManyField(blank=True, related_name='event_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
