# Generated by Django 5.1.6 on 2025-03-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0004_eventrating_dislikes_eventrating_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_closed',
            field=models.BooleanField(default=False, verbose_name='Регистрация закрыта'),
        ),
    ]
