# Generated by Django 5.1.6 on 2025-03-12 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0005_alter_event_options_remove_event_prousers_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizers',
        ),
        migrations.AddField(
            model_name='event',
            name='dop_organizatory',
            field=models.ManyToManyField(blank=True, related_name='dostupnye_meropriyatiya_organizator', to=settings.AUTH_USER_MODEL, verbose_name='Дополнительные организаторы'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizator',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='organizovannye_meropriyatiya', to=settings.AUTH_USER_MODEL, verbose_name='Организатор'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Zapis_na_meropriatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_event.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Запись на мероприятие',
                'unique_together': {('event', 'user')},
            },
        ),
    ]
