# Generated by Django 5.1.6 on 2025-03-19 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0005_event_registration_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='question',
            name='event',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_event.choice'),
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Открытый вопрос'), ('choice', 'Вопрос с вариантами ответа'), ('team', 'Добавление команды')], max_length=50)),
                ('choices', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='add_event.event')),
            ],
        ),
        migrations.AddField(
            model_name='choice',
            name='extra_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_list', to='add_event.extrainfo'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='extra_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_event.extrainfo'),
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
