# Generated by Django 5.1.6 on 2025-03-17 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0005_event_registration_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionstext', models.TextField(blank=True, max_length=100, null=True, verbose_name='questions')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_of_event', to='add_event.event', verbose_name='eventquestions')),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='event',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='user',
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('questions_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='add_event.questions')),
                ('answer', models.TextField(blank=True, max_length=100, null=True, verbose_name='answers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('add_event.questions',),
        ),
        migrations.AddField(
            model_name='event',
            name='questions',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_question', to='add_event.questions', verbose_name='Вопросы'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(blank=True, null=True, verbose_name='максимальное количество человек в команде')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventteam', to='add_event.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userteem', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_team', to='add_event.team', verbose_name='Команды'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnswerOption',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.AddField(
            model_name='event',
            name='answers',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='events_with_answer', to='add_event.answers', verbose_name='Ответы'),
            preserve_default=False,
        ),
    ]
