# Generated by Django 5.1.6 on 2025-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0006_choice_alter_useranswer_answer_remove_question_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='additional_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
