# Generated by Django 5.1.6 on 2025-03-18 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0006_questions_remove_useranswer_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='team',
            name='event',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team',
        ),
        migrations.RemoveField(
            model_name='event',
            name='teams',
        ),
        migrations.CreateModel(
            name='ExtraInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True)),
                ('field_type', models.CharField(choices=[('text', 'Открытый вопрос'), ('choice', 'Вопрос с вариантами ответа'), ('team', 'Добавление команды')], max_length=50)),
                ('choices', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_info', to='add_event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('extra_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices_list', to='add_event.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_event.choice')),
                ('extra_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_event.extrainfo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
