# Generated by Django 5.1.6 on 2025-04-06 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0008_remove_event_additional_questions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrainfo',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='choice',
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='allow_multiple',
            field=models.BooleanField(default=False, verbose_name='Разрешить выбор нескольких вариантов'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='max_team_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Максимальный размер команды'),
        ),
        migrations.AddField(
            model_name='extrainfo',
            name='min_team_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Минимальный размер команды'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='choices',
            field=models.ManyToManyField(blank=True, related_name='user_answers', to='add_event.choice'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='is_team_captain',
            field=models.BooleanField(default=False, verbose_name='Капитан команды'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(max_length=200, verbose_name='Вариант ответа'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='field_type',
            field=models.CharField(choices=[('text', 'Открытый вопрос'), ('choice', 'Вопрос с вариантами ответа'), ('team', 'Добавление команды')], max_length=50, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='extrainfo',
            name='question',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ'),
        ),
    ]
