# Generated by Django 5.1.6 on 2025-04-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_event', '0010_alter_useranswer_answer_alter_useranswer_choices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='choices',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название команды'),
        ),
    ]
